name: Tests

on:
  pull_request:
    paths:
      - '**.py'
      - 'requirements.txt'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    - name: Test with nose2
      run: |
        nose2 --with-coverage --coverage-report term-missing

    - name: Slack Notification when tests failed
      if: failure()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: ${{secrets.SLACK_CHANNEL}}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_COLOR: '#ff0000'
        SLACK_TITLE: ' :x::x::x: Tests Failed! :x::x::x:'
        SLACK_MESSAGE: "Tests Failed! Please check github!"
        SLACK_USERNAME: GitHub Actions
        SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
